### ISSUE TITLE
On Bluesky, posting messages with mentions or URL does not respect the ATProcol rules

### ISSUE THREAD

**Issue by jbuget** [jbuget/threadr-app#10]
### 🍣 Problem

We do not follow the rules of the [Bluesky API "facets" system](https://atproto.com/blog/create-post#mentions-and-links).

Thus, the URLs are displayed (and counted) as basic text.

### 🦄 Solution

Modify the `publication service` in order to follow facets rules. (thanks @ygrenzinger for the alert 😉)

**Comment by ygrenzinger** [comment]
The PR to solve this https://github.com/jbuget/threadr-app/pull/15

**Comment by jbuget** [comment]
Closed by #15
